{{- if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fluentd-elasticsearch.fullname" . }}
  labels:
    app: {{ template "fluentd-elasticsearch.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $port := .Values.service.ports }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.port }}
      {{- if $port.nodePort }}
      nodePort: {{ $port.nodePort }}
      {{- end }}
      {{- if $port.protocol }}
      protocol: {{ $port.protocol }}
      {{- end }}
kind: Endpoints
apiVersion: v1
metadata:
  name: {{ template "fluentd-elasticsearch.fullname" . }}
subsets:
  - addresses:
      - ip: 10.1.1.136
    ports:
      - port: {{ $port.port }}
  {{- end }}
{{- end }}

